### PR TITLE
Custom Podloveplayer

### PR DESCRIPTION
**Pull request by Suven**
A quick suggestion made with http://customplayer.webgeplapper.de 

screen shot 2015-03-01 at 01 46 17

Please note that I was not able to test it properly since my local ruby-env is *itching around. So IF you would like to merge it, please check if the css is being loaded correctly first.

### CODE REVIEW

**Comment by ltsavar** [comment]
Thanks a lot.
We are doing it live....

**Comment by fliiiix** [comment]
nice :+1:

**Comment by ltsavar** [comment]
Jup. Funktioniert. Danke nochmal.

**Comment by Suven** [comment]
Yay \o/ Freut mich!

**Pull request merged**
