### PR TITLE
remove heroku deploy

### PR DESCRIPTION
**Pull request by fliiiix**
after merging this also remove HEROKU_API_KEY from this repo

### CODE REVIEW

**Comment by fliiiix** [comment]
and maybe we also need to remove the heroku thingy itself?

**Comment by rb2k** [comment]
Alles raus was keine Miete zahlt.

**Comment by fliiiix** [comment]
@rb2k kannst du das heroku dingsi loeschen?

**Comment by fliiiix** [comment]
token is gone

**Pull request merged**
